[build]
  # Build configuration for HR Tools Portal
  publish = "."
  command = "echo 'Static site - no build process required'"

[build.environment]
  NODE_ENV = "production"

# Redirect configuration
[[redirects]]
  from = "/api/*"
  to = "https://wvtojojfwkryzixshczr.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Single Page Application - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# Security headers (alternative to _headers file)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment-specific configuration
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "staging" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }